### ISSUE TITLE
Unknown PDD parsing bug

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/0pdd#91]
https://github.com/EnigmaDragons/MegaBuy/commit/6038f359218e93973054245c7d9df1e9356ffd0f

https://github.com/EnigmaDragons/MegaBuy/commit/02629134003aa5515c801ec37a2c9129a350f98d

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@SilasReinagel we'll have more logs after #93

**Comment by SilasReinagel** [comment]
This one is still a big problem. We're unable to use 0PDD because of it.

**Comment by yegor256** [comment]
@SilasReinagel I can't figure out what's going on, but my best guess is that your puzzles clash into each other, because their ID's are equal. Try to use longer texts for them and see what happens. I see that you're using just a few words -- it's a bad practice. Make sure your texts are long enough.

**Comment by yegor256** [comment]
@SilasReinagel is this still an issue? We made many changes to the software since this bug was reported. I believe it's fixed already. Please, check.
